//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using NUnit.Framework;

namespace Testing
{
	[TestFixture()]
	public class UnitTestTurno
	{
		Turno t;
		Player plr1, plr2;

		[SetUp()]
		public void Init()
			{
				t = new Turno();
				
				//SE HA TENIDO
				plr1 = new Player();
				plr2 = new Player();
			}

		[Test()]
		public void SiguienteTurno ()
			{
				for(int i=1;i<=100;i++)
					{
						Assert.AreEqual(t.GetTurno(), i);
						t.SiguienteTurno();
					}
			}

		[Test()]
		public void JugadorActual ()
			{
				t.AddPlayer(plr1);
				t.AddPlayer(plr2);

				Assert.AreEqual(t.JugadorActual(), plr2);
				t.SiguienteTurno();

				Assert.AreEqual(t.JugadorActual(), plr1);
				t.SiguienteTurno();

				Assert.AreEqual(t.JugadorActual(), plr2);
			}
	}
}

