//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using NUnit.Framework;

namespace Testing
{
	[TestFixture()]
	public class UnitTestPlayer
	{
		//HA SIDO NECESARIO HACER QUE PLAYER NO HEREDE DE MonoBehaviour
		Player plr;
		[SetUp()]
		public void Init()
		{
			plr = new Player();
		}

		[Test()]
		public void Defecto()
			{
				Assert.AreEqual(plr.GetDinero(),1000);
			}

		[Test()]
		public void Aumentar()
			{
				plr.Aumentar(500);
				Assert.AreEqual(1500, plr.GetDinero());

				plr.Aumentar(-500);
				Assert.AreEqual(1500, plr.GetDinero());
			}

		[Test()]
		public void Pagar()
			{
				//Player inicializado a 1000 de dinero
				Assert.AreEqual(true, plr.Pagar(500));
				Assert.AreEqual(500, plr.GetDinero());

				//Ahora el player deberia tener 500 de dinero
				Assert.AreEqual(true, plr.Pagar(500));
				Assert.AreEqual(0, plr.GetDinero());

				//Ahora el player deberia tener 0 de dinero
				Assert.AreEqual(false, plr.Pagar(500));
				Assert.AreEqual(0, plr.GetDinero());
			}
	}
}

