public enum F_Unidades
	{
		INFANTERIA_LIGERA,
		INFANTERIA_PESADA,
		TANQUE,
		ARTILLERIAT,
		CAZA,
		BOMBARDERO,
		DESTRUCTOR,
		ARTILLERIAA
	}

public enum costes
{
	COSTE_INFANTERIA_LIGERA = 500,
	COSTE_INFANTERIA_PESADA = 700,
	COSTE_TANQUE = 1000,
	COSTE_ARTILLERIAT = 1000,
	COSTE_CAZA = 2000,
	COSTE_BOMBARDERO = 2500,
	COSTE_DESTRUCTOR = 2000,
	COSTE_ARTILLERIAA = 2500
}